version: '3.8'

services:
  tragestudios-api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: tragestudios-api
    restart: unless-stopped
    env_file: .env
    networks:
      - tragestudios-network
      - tragestudios-net

  tragestudios-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tragestudios-website
    ports:
      - "127.0.0.1:8080:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - tragestudios-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:80"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  tragestudios-network:
    driver: bridge
  tragestudios-net:
    external: true
